version: '3'
services:
  backend:
    restart: always
    container_name: aws_backend
    build: ./backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    restart: always
    container_name: aws_frontend
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend